# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrum_info_editor.ui',
# licensing of 'spectrum_info_editor.ui' applies.
#
# Created: Sun May 10 21:09:44 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SpectrumInfoEditor(object):
    def setupUi(self, SpectrumInfoEditor):
        SpectrumInfoEditor.setObjectName("SpectrumInfoEditor")
        SpectrumInfoEditor.resize(333, 336)
        SpectrumInfoEditor.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(SpectrumInfoEditor)
        self.buttonBox.setGeometry(QtCore.QRect(10, 300, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(SpectrumInfoEditor)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 316, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_layout.setContentsMargins(0, 0, 0, 0)
        self.grid_layout.setObjectName("grid_layout")
        self.label_location = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_location.setObjectName("label_location")
        self.grid_layout.addWidget(self.label_location, 4, 0, 1, 1)
        self.lineedit_area_avg_y = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineedit_area_avg_y.setObjectName("lineedit_area_avg_y")
        self.grid_layout.addWidget(self.lineedit_area_avg_y, 7, 2, 1, 1)
        self.lineedit_dataset = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineedit_dataset.setReadOnly(True)
        self.lineedit_dataset.setObjectName("lineedit_dataset")
        self.grid_layout.addWidget(self.lineedit_dataset, 3, 1, 1, 2)
        self.label_dataset = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_dataset.setObjectName("label_dataset")
        self.grid_layout.addWidget(self.label_dataset, 3, 0, 1, 1)
        self.label_spectrum_type = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_spectrum_type.setObjectName("label_spectrum_type")
        self.grid_layout.addWidget(self.label_spectrum_type, 2, 0, 1, 1)
        self.combobox_avg_mode = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combobox_avg_mode.setObjectName("combobox_avg_mode")
        self.combobox_avg_mode.addItem("")
        self.combobox_avg_mode.addItem("")
        self.grid_layout.addWidget(self.combobox_avg_mode, 5, 1, 1, 2)
        self.label_plot_color = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_plot_color.setObjectName("label_plot_color")
        self.grid_layout.addWidget(self.label_plot_color, 8, 0, 1, 1)
        self.label_area_avg_y = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_area_avg_y.setObjectName("label_area_avg_y")
        self.grid_layout.addWidget(self.label_area_avg_y, 7, 1, 1, 1)
        self.lineedit_location = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineedit_location.setReadOnly(True)
        self.lineedit_location.setObjectName("lineedit_location")
        self.grid_layout.addWidget(self.lineedit_location, 4, 1, 1, 2)
        self.label_area_avg_x = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_area_avg_x.setObjectName("label_area_avg_x")
        self.grid_layout.addWidget(self.label_area_avg_x, 6, 1, 1, 1)
        self.grid_layout_plot_color = QtWidgets.QGridLayout()
        self.grid_layout_plot_color.setSpacing(0)
        self.grid_layout_plot_color.setObjectName("grid_layout_plot_color")
        self.lineedit_plot_color = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineedit_plot_color.setObjectName("lineedit_plot_color")
        self.grid_layout_plot_color.addWidget(self.lineedit_plot_color, 0, 0, 1, 1)
        self.button_plot_color = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_plot_color.setMinimumSize(QtCore.QSize(32, 32))
        self.button_plot_color.setObjectName("button_plot_color")
        self.grid_layout_plot_color.addWidget(self.button_plot_color, 0, 1, 1, 1)
        self.grid_layout_plot_color.setColumnStretch(0, 10)
        self.grid_layout.addLayout(self.grid_layout_plot_color, 8, 1, 1, 2)
        self.label_avg_mode = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_avg_mode.setObjectName("label_avg_mode")
        self.grid_layout.addWidget(self.label_avg_mode, 5, 0, 1, 1)
        self.lineedit_area_avg_x = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineedit_area_avg_x.setObjectName("lineedit_area_avg_x")
        self.grid_layout.addWidget(self.lineedit_area_avg_x, 6, 2, 1, 1)
        self.label_description = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_description.setObjectName("label_description")
        self.grid_layout.addWidget(self.label_description, 0, 0, 1, 1)
        self.lineedit_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineedit_name.setObjectName("lineedit_name")
        self.grid_layout.addWidget(self.lineedit_name, 1, 0, 1, 3)
        self.label_area_avg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_area_avg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_area_avg.setObjectName("label_area_avg")
        self.grid_layout.addWidget(self.label_area_avg, 6, 0, 1, 1)
        self.lineedit_spectrum_type = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineedit_spectrum_type.setReadOnly(True)
        self.lineedit_spectrum_type.setObjectName("lineedit_spectrum_type")
        self.grid_layout.addWidget(self.lineedit_spectrum_type, 2, 1, 1, 2)
        self.grid_layout.setColumnStretch(0, 10)
        self.label_location.setBuddy(self.lineedit_location)
        self.label_dataset.setBuddy(self.lineedit_dataset)
        self.label_plot_color.setBuddy(self.lineedit_plot_color)
        self.label_area_avg_y.setBuddy(self.lineedit_area_avg_y)
        self.label_area_avg_x.setBuddy(self.lineedit_area_avg_x)
        self.label_avg_mode.setBuddy(self.combobox_avg_mode)
        self.label_description.setBuddy(self.lineedit_name)

        self.retranslateUi(SpectrumInfoEditor)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), SpectrumInfoEditor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), SpectrumInfoEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(SpectrumInfoEditor)
        SpectrumInfoEditor.setTabOrder(self.lineedit_name, self.lineedit_spectrum_type)
        SpectrumInfoEditor.setTabOrder(self.lineedit_spectrum_type, self.lineedit_dataset)
        SpectrumInfoEditor.setTabOrder(self.lineedit_dataset, self.lineedit_location)
        SpectrumInfoEditor.setTabOrder(self.lineedit_location, self.combobox_avg_mode)
        SpectrumInfoEditor.setTabOrder(self.combobox_avg_mode, self.lineedit_area_avg_x)
        SpectrumInfoEditor.setTabOrder(self.lineedit_area_avg_x, self.lineedit_area_avg_y)
        SpectrumInfoEditor.setTabOrder(self.lineedit_area_avg_y, self.lineedit_plot_color)
        SpectrumInfoEditor.setTabOrder(self.lineedit_plot_color, self.button_plot_color)

    def retranslateUi(self, SpectrumInfoEditor):
        SpectrumInfoEditor.setWindowTitle(QtWidgets.QApplication.translate("SpectrumInfoEditor", "Spectrum Information", None, -1))
        self.label_location.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "Location", None, -1))
        self.label_dataset.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "Data set", None, -1))
        self.label_spectrum_type.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "Spectrum type", None, -1))
        self.combobox_avg_mode.setItemText(0, QtWidgets.QApplication.translate("SpectrumInfoEditor", "Mean", None, -1))
        self.combobox_avg_mode.setItemText(1, QtWidgets.QApplication.translate("SpectrumInfoEditor", "Median", None, -1))
        self.label_plot_color.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "Plot color", None, -1))
        self.label_area_avg_y.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "Y", None, -1))
        self.label_area_avg_x.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "X", None, -1))
        self.button_plot_color.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "...", None, -1))
        self.label_avg_mode.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "Average mode", None, -1))
        self.label_description.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "Name:", None, -1))
        self.label_area_avg.setText(QtWidgets.QApplication.translate("SpectrumInfoEditor", "Area-average size", None, -1))

