"""
patch_cv2_config_for_bundle.py — Rewrite bundled OpenCV config files after PyInstaller.

Background
----------
After `pyinstaller` builds `dist/WISER/_internal/`, the `cv2/` directory contains
config files such as `config-3.9.py` generated from the *build* machine's conda/micromamba
environment.  Those files hard-code absolute paths like:

    PYTHON_EXTENSIONS_PATHS = [
        os.path.join('/opt/micromamba/envs/wiser-prod/lib/python3.9/site-packages/cv2',
                     'python-3.9'),
    ] + PYTHON_EXTENSIONS_PATHS

When the bundle runs on *any other machine* (or inside a spawned child process on macOS CI),
those build-machine paths do not exist, the wrong directory ends up first on sys.path, and
OpenCV's bootstrap re-imports cv2/__init__.py instead of the bundled .so — causing a
RecursionError.

What this script does
---------------------
For each `config-M.m.py` found under the target cv2 directory it writes a clean replacement:

* Frozen (getattr(sys, "frozen", False) is True):
  PYTHON_EXTENSIONS_PATHS is set to the matching `python-M.m` folder under sys._MEIPASS/cv2,
  which is exactly where PyInstaller places the bundled native extension.

* Non-frozen (dev/conda import):
  Falls back to the stock-like pattern — extension dir next to cv2/__init__.py — without
  baking any absolute build-machine path.

`config.py` (non-versioned, controls BINARIES_PATHS) is intentionally not patched here.
If future failures point at BINARIES_PATHS, apply the same pattern in a separate step.

Usage
-----
    python src/devtools/patch_cv2_config_for_bundle.py dist/WISER/_internal/cv2

This is invoked automatically by `make build-mac`, `make build-win`, and `make build-linux`
immediately after pyinstaller finishes.
"""

import re
import sys
from pathlib import Path


# Template for the frozen-aware replacement.
# {major_minor} is e.g. "3.9"
_CONFIG_TEMPLATE = """\
# Generated by src/devtools/patch_cv2_config_for_bundle.py — do not edit by hand.
# See that script for the rationale.
import os
import sys

if getattr(sys, "frozen", False):
    # Running inside a PyInstaller bundle.  sys._MEIPASS points at _internal/.
    # The bundled native extension lives at _internal/cv2/python-{major_minor}/.
    PYTHON_EXTENSIONS_PATHS = [
        os.path.join(sys._MEIPASS, "cv2", "python-{major_minor}")
    ] + PYTHON_EXTENSIONS_PATHS
else:
    # Normal dev/conda import: resolve relative to this config file's location.
    PYTHON_EXTENSIONS_PATHS = [
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "python-{major_minor}")
    ] + PYTHON_EXTENSIONS_PATHS
"""

_VERSIONED_CONFIG_PATTERN = re.compile(r"^config-(\d+)\.(\d+)\.py$")


def patch_cv2_directory(cv2_dir: Path) -> None:
    """Overwrite every versioned config-M.m.py in cv2_dir with the frozen-aware template."""
    if not cv2_dir.is_dir():
        print(f"[patch_cv2] ERROR: directory not found: {cv2_dir}", file=sys.stderr)
        sys.exit(1)

    patched = []
    for path in sorted(cv2_dir.iterdir()):
        match = _VERSIONED_CONFIG_PATTERN.match(path.name)
        if not match:
            continue
        major, minor = match.group(1), match.group(2)
        major_minor = f"{major}.{minor}"
        new_content = _CONFIG_TEMPLATE.format(major_minor=major_minor)
        path.write_text(new_content, encoding="utf-8")
        print(f"[patch_cv2] Patched {path} (python-{major_minor})")
        patched.append(path)

    if not patched:
        print(
            f"[patch_cv2] ERROR: no versioned config-M.m.py files found in {cv2_dir}",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"[patch_cv2] Done — patched {len(patched)} file(s).")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(
            f"Usage: python {Path(__file__).name} <path/to/bundled/cv2>",
            file=sys.stderr,
        )
        sys.exit(1)

    patch_cv2_directory(Path(sys.argv[1]))
